### ISSUE TITLE
Max Call Stack Size Exceeded for responses with recursive references.

### ISSUE THREAD

**Issue by avneeshrai** [Azure/oav#115]
Instance can be seen in PR: https://github.com/Azure/azure-rest-api-specs/pull/1209
For example with name: "ReplicationJobs_Get.json"
And API with operation ID: "ReplicationJobs_Get"

**Comment by vishrutshah** [comment]
Investigating...

**Comment by vishrutshah** [comment]
Based on the initial investigation it seems like we are running into infinite loop in search for discriminator. 

```
vishrut@mac oav (master) $ node cli.js validate-example /Users/vishrut/git-repos/azure-rest-api-specs/arm-recoveryservicessiterecovery/2016-08-10/swagger/service.json -o ReplicationJobs_Get
in cloning
in cloning
in cloning
in cloning
in cloning
in cloning
Hello i am here
RangeError: Maximum call stack size exceeded
    at Array.join (native)
    at getObject (/Users/vishrut/git-repos/oav/node_modules/sway/lib/helpers.js:554:67)
    at searchDiscriminator (/Users/vishrut/git-repos/oav/node_modules/sway/lib/helpers.js:646:31)
    at searchDiscriminator (/Users/vishrut/git-repos/oav/node_modules/sway/lib/helpers.js:661:13)
    at searchDiscriminator (/Users/vishrut/git-repos/oav/node_modules/sway/lib/helpers.js:646:11)
    at searchDiscriminator (/Users/vishrut/git-repos/oav/node_modules/sway/lib/helpers.js:661:13)
    at searchDiscriminator (/Users/vishrut/git-repos/oav/node_modules/sway/lib/helpers.js:646:11)
    at searchDiscriminator (/Users/vishrut/git-repos/oav/node_modules/sway/lib/helpers.js:661:13)
    at searchDiscriminator (/Users/vishrut/git-repos/oav/node_modules/sway/lib/helpers.js:646:11)
    at searchDiscriminator (/Users/vishrut/git-repos/oav/node_modules/sway/lib/helpers.js:661:13)
Hello i am here too
error: Found errors in validating the response with statusCode "200" for x-ms-example "Gets the job details." in operation "ReplicationJobs_Get".:
 
{ code: 'RESPONSE_VALIDATION_ERROR',
  message: 'Found errors in validating the response with statusCode "200" for x-ms-example "Gets the job details." in operation "ReplicationJobs_Get".',
  innerErrors: 
   [ { code: 'INVALID_RESPONSE_BODY',
       errors: 
        [ { code: undefined,
            message: 'Maximum call stack size exceeded',
            path: undefined } ],
       message: 'Invalid body: Maximum call stack size exceeded',
       path: [] } ] }

```

@amarzavery I am looking into this once but if you get a chance to skim through let me know :)

**Comment by amarzavery** [comment]
issue fixed with this PR https://github.com/amarzavery/sway/pull/8
