### ISSUE TITLE
running oav with validate-example option on composite spec throws operationIds must be of type 'string'

### ISSUE THREAD

**Issue by solankisamir** [Azure/oav#129]
C:\github\azure-rest-api-specs\arm-apimanagement>oav validate-example compositeApiManagementClient.json -l info
info: Validating "examples" and "x-ms-examples" in  ./2017-03-01/swagger/apimanagement.json:

error:  Error: operationIds parameter must be of type 'string'.
    at SpecValidator.validateOperations (C:\Users\sasolank\AppData\Roaming\npm\node_modules\oav\lib\validators\specValidator.js:464:13)
    at C:\Users\sasolank\AppData\Roaming\npm\node_modules\oav\lib\validate.js:98:15
    at process._tickCallback (internal/process/next_tick.js:109:7)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:393:7)
    at startup (bootstrap_node.js:150:9)
    at bootstrap_node.js:508:3
error:  Error: operationIds parameter must be of type 'string'.
    at SpecValidator.validateOperations (C:\Users\sasolank\AppData\Roaming\npm\node_modules\oav\lib\validators\specValidator.js:464:13)
    at C:\Users\sasolank\AppData\Roaming\npm\node_modules\oav\lib\validate.js:98:15
    at process._tickCallback (internal/process/next_tick.js:109:7)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:393:7)
    at startup (bootstrap_node.js:150:9)
    at bootstrap_node.js:508:3
(node:17256) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): Error: operationIds parameter must be of type 'string'.

**Comment by solankisamir** [comment]
with 20 files.. it is difficult to figure out which spec has the issue.

**Comment by veronicagg** [comment]
@solankisamir are you still seeing this issue?, we've done lots of updates and not using composite anymore, but readme files. Let's close the issue if not valid anymore.

**Comment by solankisamir** [comment]
no I am good.
