### ISSUE TITLE
Exit code for running Azure swagger files with errors

### ISSUE THREAD

**Issue by hellosnow** [Azure/oav#163]
We’re running `oav generate-wireformat` against Azure swagger file https://github.com/Azure/azure-rest-api-specs/blob/current/specification/automation/resource-manager/Microsoft.Automation/2015-10-31/credential.json to generate `x-ms-examples` content, and it fails with invalid parameters when resolving this example https://github.com/Azure/azure-rest-api-specs/blob/current/specification/automation/resource-manager/Microsoft.Automation/2015-10-31/examples/deleteCertificate.json. 

In this case, we think it’s content issues due to missing parameter. Our question is: when running in cmd, besides the log message, do we have any clue to indicate the command fails? We testes the $LASTEXITCODE in powershell and %loglevel% in cmd is 0 here, while we expected it as 1. Could we throw Error(“”) directly in JavaScript, to force node.exe return the exit code as 1, or you have other ideas? Thanks.

```ps
PS D:\Work\PowerShell> oav generate-wireformat D:\Code\azure-rest-api-specs\specification\automation\resource-manager\Microsoft.Automation\2015-10-31\credential.json
error:  Error: pathTemplate: /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Automation/automationAccounts/{automationAccountName}/credentials/{credentialName} contains the path parameter credentialName however, it is not present in [object Object] - {
  "resourceGroupName": "rg",
  "automationAccountName": "myAutomationAccount20",
  "subscriptionId": "subid"
}.The value of the path parameter can either be a "string" of the form { credentialName: "some sample value" } or it can be an "object" of the form { "credentialName": { value: "some sample value", skipUrlEncoding: true } }.
    at C:\Users\jehuan\AppData\Roaming\npm\node_modules\oav\node_modules\ms-rest\lib\webResource.js:178:19
    at Array.forEach (native)
    at WebResource.prepare (C:\Users\jehuan\AppData\Roaming\npm\node_modules\oav\node_modules\ms-rest\lib\webResource.js:174:18)
at WireFormatGenerator.processRequest (C:\Users\jehuan\AppData\Roaming\npm\node_modules\oav\lib\wireFormatGenerator.js:326:23)
PS D:\Work\PowerShell> $LASTEXITCODE
0

```

**Comment by amarzavery** [comment]
This issue has been resolved.
```bash
D:\sdk\oav>oav generate-wireformat https://github.com/Azure/azure-rest-api-specs/blob/current/specification/automation/resource-manager/Microsoft.Automation/stable/2015-10-31/credential.json
error:  Error: pathTemplate: /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Automation/automationAccounts/{automationAccountName}/credentials/{credentialName} contains the path parameter credentialName however, it is not present in [object Object] - {
  "resourceGroupName": "rg",
  "automationAccountName": "myAutomationAccount20",
  "subscriptionId": "subid"
}.The value of the path parameter can either be a "string" of the form { credentialName: "some sample value" } or it can be an "object" of the form { "credentialName": { value: "some sample value", skipUrlEncoding: true } }.
    at D:\sdk\oav\node_modules\ms-rest\lib\webResource.js:182:19
    at Array.forEach (<anonymous>)
    at WebResource.prepare (D:\sdk\oav\node_modules\ms-rest\lib\webResource.js:178:18)
    at WireFormatGenerator.processRequest (D:\sdk\oav\lib\wireFormatGenerator.js:333:23)
    at WireFormatGenerator.processXmsExamples (D:\sdk\oav\lib\wireFormatGenerator.js:252:34)
    at WireFormatGenerator.processOperation (D:\sdk\oav\lib\wireFormatGenerator.js:231:10)
    at WireFormatGenerator.processOperations (D:\sdk\oav\lib\wireFormatGenerator.js:220:12)
    at D:\sdk\oav\lib\validate.js:189:17
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

D:\sdk\oav>echo %ERRORLEVEL%
1

D:\sdk\oav>
```
/cc @salameer @mcardosos

**Comment by hellosnow** [comment]
Thanks! @amarzavery
