### ISSUE TITLE
Running model validation via autorest throws an exception for some specs in azure-rest-api-specs repo

### ISSUE THREAD

**Issue by veronicagg** [Azure/oav#182]
Needs investigation, as running it via oav only I'm not seeing the issue and couldn't detect it under the debugger, but when running autorest command I do see the same issue
```
Model Validation on configuration file: "C:/Source/azure-rest-api-specs/specification/monitor/resource-manager/readme.md"
autorest --version=2.0.4174 --model-validator --message-format=json C:/Source/azure-rest-api-specs/specification/monitor/resource-manager/readme.md
An error occurred while executing JSON.parse() on the output for autorest --version=2.0.4174 --model-validator --message-format=json C:/Source/azure-rest-api-specs/specification/monitor/resource-manager/readme.md:
(node:8320) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property \'slice\' of undefined\n(node:8320) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.]'
SyntaxError: Unexpected token ( in JSON at position 17778
    at JSON.parse (<anonymous>)
    at runCmd (C:\Source\azure-rest-api-specs\scripts\getStatus.js:70:27)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

Model Validation on configuration file: "C:/Source/azure-rest-api-specs/specification/automation/resource-manager/readme.md"
autorest --version=2.0.4174 --model-validator --message-format=json C:/Source/azure-rest-api-specs/specification/automation/resource-manager/readme.md
An error occurred while executing JSON.parse() on the output for autorest --version=2.0.4174 --model-validator --message-format=json C:/Source/azure-rest-api-specs/specification/automation/resource-manager/readme.md:
SyntaxError: Unexpected token ( in JSON at position 13233
    at JSON.parse (<anonymous>)
    at runCmd (C:\Source\azure-rest-api-specs\scripts\getStatus.js:70:27)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

Model Validation on configuration file: "C:/Source/azure-rest-api-specs/specification/appinsights/resource-manager/readme.md"
autorest --version=2.0.4174 --model-validator --message-format=json C:/Source/azure-rest-api-specs/specification/appinsights/resource-manager/readme.md
An error occurred while executing JSON.parse() on the output for autorest --version=2.0.4174 --model-validator --message-format=json C:/Source/azure-rest-api-specs/specification/appinsights/resource-manager/readme.md:
SyntaxError: Unexpected token E in JSON at position 567
    at JSON.parse (<anonymous>)
    at runCmd (C:\Source\azure-rest-api-specs\scripts\getStatus.js:70:27)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by veronicagg** [comment]
@shawns1 FYI

**Comment by shawns1** [comment]
Thanks @veronicagg.  Let me know if we need to bump or remove the AutoRest version (2.0.4174) specified in our CI system once you are done.  The getStatus.js file will need to be updated.

**Comment by veronicagg** [comment]
@shawns1 Per the latest release of autorest, if you have the latest version installed on the system where you're running the script, you can remove the --version switch from the command. The latest release of autorest contains model validation. 
This specific issue still needs investigation, thanks.
