### ISSUE TITLE
OAV 2.12.0: no such file or directory markdownReport.handlebars

### ISSUE THREAD

**Issue by molson194** [Azure/oav#783]
The validate-spec command in version 2.11.10 of OAV was successfully ran, but when upgrading to 2.12.0, I started getting the error below.

Command Run:
```oav validate-spec "<PATH TO SWAGGER FILE>"```

Error:
```
`node:internal/fs/utils:344
    throw err;
    ^

Error: ENOENT: no such file or directory, open 'C:\npm\prefix\node_modules\oav\dist\lib\apiScenario\templates\markdownReport.handlebars'
    at Object.openSync (node:fs:585:3)
    at Object.readFileSync (node:fs:453:35)
    at Object.exports.compileHandlebarsTemplate (C:\npm\prefix\node_modules\oav\dist\lib\apiScenario\markdownReport.js:94:41)
    at Object.<anonymous> (C:\npm\prefix\node_modules\oav\dist\lib\apiScenario\markdownReport.js:99:44)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18) {
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: 'C:\\npm\\prefix\\node_modules\\oav\\dist\\lib\\apiScenario\\templates\\markdownReport.handlebars'
}
```

Thanks in advance for any help!

**Comment by raych1** [comment]
@molson194 , thanks for reporting the issue. This issue was resolved in version 2.12.1.
