### ISSUE TITLE
Failed to load cognitive language service data-plane swagger

### ISSUE THREAD

**Issue by leniatgh** [Azure/oav#898]
When executing `oav run specification/cognitiveservices/data-plane/Language/preview/2022-10-01-preview/scenarios/ConversationAnalysis.yaml --tag release_2022_10_01_preview -e ~/dogfooding/test-apiscenario/.env`, the jsonLoader throws exception:

```
{
  stack: 'MissingPointerError: Token "Error" does not exist.\n' +
    '    at Pointer.resolve (/home/me/workspace/oav/node_modules/@apidevtools/json-schema-ref-parser/lib/pointer.js:94:13)\n' +
    '    at $Ref.resolve (/home/me/workspace/oav/node_modules/@apidevtools/json-schema-ref-parser/lib/ref.js:124:20)\n' +
    '    at $Refs._resolve (/home/me/workspace/oav/node_modules/@apidevtools/json-schema-ref-parser/lib/refs.js:156:15)\n' +
    '    at dereference$Ref (/home/me/workspace/oav/node_modules/@apidevtools/json-schema-ref-parser/lib/dereference.js:133:23)\n' +
    '    at crawl (/home/me/workspace/oav/node_modules/@apidevtools/json-schema-ref-parser/lib/dereference.js:62:28)\n' +
    '    at crawl (/home/me/workspace/oav/node_modules/@apidevtools/json-schema-ref-parser/lib/dereference.js:71:30)\n' +
    '    at crawl (/home/me/workspace/oav/node_modules/@apidevtools/json-schema-ref-parser/lib/dereference.js:71:30)\n' +
    '    at crawl (/home/me/workspace/oav/node_modules/@apidevtools/json-schema-ref-parser/lib/dereference.js:71:30)\n' +
    '    at dereference (/home/me/workspace/oav/node_modules/@apidevtools/json-schema-ref-parser/lib/dereference.js:19:22)\n' +
    '    at $RefParser.dereference (/home/me/workspace/oav/node_modules/@apidevtools/json-schema-ref-parser/lib/index.js:269:5)\n' +
    '    at async JsonLoader.load (/home/me/workspace/oav/dist/lib/swagger/jsonLoader.js:127:30)\n' +
    '    at async SwaggerLoader.load (/home/me/workspace/oav/dist/lib/swagger/swaggerLoader.js:38:30)\n' +
    '    at async LiveValidatorLoader.load (/home/me/workspace/oav/dist/lib/liveValidation/liveValidatorLoader.js:104:22)\n' +
    '    at async LiveValidator.getSwaggerInitializer (/home/me/workspace/oav/dist/lib/liveValidation/liveValidator.js:571:20)\n' +
    '    at async LiveValidator.initialize (/home/me/workspace/oav/dist/lib/liveValidation/liveValidator.js:175:26)\n' +
    '    at async NewmanReportValidator.initialize (/home/me/workspace/oav/dist/lib/apiScenario/newmanReportValidator.js:94:13)',
  code: 'EMISSINGPOINTER',
  message: 'Token "Error" does not exist.',
  source: '/home/me/workspace/azure-rest-api-specs/specification/cognitiveservices/data-plane/Language/preview/2022-10-01-preview/analyzetext.json',
  path: null,
  toJSON: [Function: toJSON],
  name: 'MissingPointerError',
  footprint: 'null+/home/me/workspace/azure-rest-api-specs/specification/cognitiveservices/data-plane/Language/preview/2022-10-01-preview/analyzetext.json+EMISSINGPOINTER+Token "Error" does not exist.',
  toString: [Function: toString]
}
error
{
  level: '\x1B[31merror\x1B[39m',
  message: 'Failed to load spec /home/me/workspace/azure-rest-api-specs/specification/cognitiveservices/data-plane/Language/preview/2022-10-01-preview/analyzetext.json'
}
{
  stack: 'MissingPointerError: Token "Error" does not exist.\n' +
    '    at Pointer.resolve (/home/me/workspace/oav/node_modules/@apidevtools/json-schema-ref-parser/lib/pointer.js:94:13)\n' +
    '    at $Ref.resolve (/home/me/workspace/oav/node_modules/@apidevtools/json-schema-ref-parser/lib/ref.js:124:20)\n' +
    '    at $Refs._resolve (/home/me/workspace/oav/node_modules/@apidevtools/json-schema-ref-parser/lib/refs.js:156:15)\n' +
    '    at dereference$Ref (/home/me/workspace/oav/node_modules/@apidevtools/json-schema-ref-parser/lib/dereference.js:133:23)\n' +
    '    at crawl (/home/me/workspace/oav/node_modules/@apidevtools/json-schema-ref-parser/lib/dereference.js:62:28)\n' +
    '    at crawl (/home/me/workspace/oav/node_modules/@apidevtools/json-schema-ref-parser/lib/dereference.js:71:30)\n' +
    '    at crawl (/home/me/workspace/oav/node_modules/@apidevtools/json-schema-ref-parser/lib/dereference.js:71:30)\n' +
    '    at crawl (/home/me/workspace/oav/node_modules/@apidevtools/json-schema-ref-parser/lib/dereference.js:71:30)\n' +
    '    at crawl (/home/me/workspace/oav/node_modules/@apidevtools/json-schema-ref-parser/lib/dereference.js:71:30)\n' +
    '    at dereference (/home/me/workspace/oav/node_modules/@apidevtools/json-schema-ref-parser/lib/dereference.js:19:22)\n' +
    '    at $RefParser.dereference (/home/me/workspace/oav/node_modules/@apidevtools/json-schema-ref-parser/lib/index.js:269:5)\n' +
    '    at async JsonLoader.load (/home/me/workspace/oav/dist/lib/swagger/jsonLoader.js:127:30)\n' +
    '    at async SwaggerLoader.load (/home/me/workspace/oav/dist/lib/swagger/swaggerLoader.js:38:30)\n' +
    '    at async LiveValidatorLoader.load (/home/me/workspace/oav/dist/lib/liveValidation/liveValidatorLoader.js:104:22)\n' +
    '    at async LiveValidator.getSwaggerInitializer (/home/me/workspace/oav/dist/lib/liveValidation/liveValidator.js:571:20)\n' +
    '    at async LiveValidator.initialize (/home/me/workspace/oav/dist/lib/liveValidation/liveValidator.js:175:26)',
  code: 'EMISSINGPOINTER',
  message: 'Token "Error" does not exist.',
  source: '/home/me/workspace/azure-rest-api-specs/specification/cognitiveservices/data-plane/Language/preview/2022-10-01-preview/analyzetext-authoring.json',
  path: null,
  toJSON: [Function: toJSON],
  name: 'MissingPointerError',
  footprint: 'null+/home/me/workspace/azure-rest-api-specs/specification/cognitiveservices/data-plane/Language/preview/2022-10-01-preview/analyzetext-authoring.json+EMISSINGPOINTER+Token "Error" does not exist.',
  toString: [Function: toString]
}
error
{
  level: '\x1B[31merror\x1B[39m',
  message: 'Failed to load spec /home/me/workspace/azure-rest-api-specs/specification/cognitiveservices/data-plane/Language/preview/2022-10-01-preview/analyzetext-authoring.json'
}
```

**Comment by xiaoxuqi-ms** [comment]
Working on: https://github.com/Azure/oav/pull/964
