### ISSUE TITLE
ModelValidation fails with error: validateOperations - ErrorMessage: parameter.includes is not a function

### ISSUE THREAD

**Issue by abatishchev** [Azure/oav#903]
A PR check to the private repo fails at 

```
Validating x-ms-examples in /mnt/vss/_work/1/azure-rest-api-specs-pr/specification/throttling/resource-manager/Microsoft.Throttling/preview/2022-06-01-preview/throttling.json

error: 
Unexpected runtime exception:

{
  message: 'Detail error:parameter.includes is not a function.ErrorStack:TypeError: parameter.includes is not a function\n' +
    '    at SwaggerExampleValidator.schemaIssuesToModelValidationIssues (/mnt/vss/_work/_tasks/AzureApiValidation_5654d05d-82c1-48da-ad8f-161b817f6d41/0.0.44/private/azure-swagger-validation/azureSwaggerValidation/dist/main.js:199966:67)\n' +
    '    at SwaggerExampleValidator.validateResponse (/mnt/vss/_work/_tasks/AzureApiValidation_5654d05d-82c1-48da-ad8f-161b817f6d41/0.0.44/private/azure-swagger-validation/azureSwaggerValidation/dist/main.js:199711:22)\n' +
    '    at SwaggerExampleValidator.validateOperation (/mnt/vss/_work/_tasks/AzureApiValidation_5654d05d-82c1-48da-ad8f-161b817f6d41/0.0.44/private/azure-swagger-validation/azureSwaggerValidation/dist/main.js:199634:18)\n' +
    '    at onOperation (/mnt/vss/_work/_tasks/AzureApiValidation_5654d05d-82c1-48da-ad8f-161b817f6d41/0.0.44/private/azure-swagger-validation/azureSwaggerValidation/dist/main.js:199603:36)\n' +
    '    at Object.exports.traverseSwaggerAsync (/mnt/vss/_work/_tasks/AzureApiValidation_5654d05d-82c1-48da-ad8f-161b817f6d41/0.0.44/private/azure-swagger-validation/azureSwaggerValidation/dist/main.js:202157:54)\n' +
    '    at async SwaggerExampleValidator.validateOperations (/mnt/vss/_work/_tasks/AzureApiValidation_5654d05d-82c1-48da-ad8f-161b817f6d41/0.0.44/private/azure-swagger-validation/azureSwaggerValidation/dist/main.js:199592:13)\n' +
    '    at async NewModelValidator.validateOperations (/mnt/vss/_work/_tasks/AzureApiValidation_5654d05d-82c1-48da-ad8f-161b817f6d41/0.0.44/private/azure-swagger-validation/azureSwaggerValidation/dist/main.js:200038:9)\n' +
    '    at async /mnt/vss/_work/_tasks/AzureApiValidation_5654d05d-82c1-48da-ad8f-161b817f6d41/0.0.44/private/azure-swagger-validation/azureSwaggerValidation/dist/main.js:205224:13\n' +
    '    at async Object.runScript [as run] (/mnt/vss/_work/_tasks/AzureApiValidation_5654d05d-82c1-48da-ad8f-161b817f6d41/0.0.44/private/azure-swagger-validation/azureSwaggerValidation/dist/main.js:249518:28)\n' +
    '    at async main (/mnt/vss/_work/_tasks/AzureApiValidation_5654d05d-82c1-48da-ad8f-161b817f6d41/0.0.44/private/azure-swagger-validation/azureSwaggerValidation/dist/main.js:249236:9)',
  level: '\x1B[31merror\x1B[39m'
}
```

See https://github.com/Azure/azure-rest-api-specs-pr/pull/9674/checks?check_run_id=9402602690
and https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1978790&view=logs&j=14c5c170-9612-5b44-a650-13d3ca524cf8&t=a1928b1b-77e4-58b6-0247-4cedb38901b4

Relevant code:

https://github.com/Azure/oav/blob/e839be11c60b754441f4410df58fddbdbe54de6f/lib/swaggerValidator/modelValidator.ts#L615-L620

See also https://github.com/Azure/oav/pull/855 for a similar error.

**Comment by abatishchev** [comment]
Still fails with the same error:

```
{
  message: 'Detail error:parameter.includes is not a function.ErrorStack:TypeError: parameter.includes is not a function\n' +
    '    at SwaggerExampleValidator.schemaIssuesToModelValidationIssues (/mnt/vss/_work/_tasks/AzureApiValidation_5654d05d-82c1-48da-ad8f-161b817f6d41/0.0.45/private/azure-swagger-validation/azureSwaggerValidation/dist/main.js:199966:67)\n' +
    '    at SwaggerExampleValidator.validateResponse (/mnt/vss/_work/_tasks/AzureApiValidation_5654d05d-82c1-48da-ad8f-161b817f6d41/0.0.45/private/azure-swagger-validation/azureSwaggerValidation/dist/main.js:199711:22)\n' +
    '    at SwaggerExampleValidator.validateOperation (/mnt/vss/_work/_tasks/AzureApiValidation_5654d05d-82c1-48da-ad8f-161b817f6d41/0.0.45/private/azure-swagger-validation/azureSwaggerValidation/dist/main.js:199634:18)\n' +
    '    at onOperation (/mnt/vss/_work/_tasks/AzureApiValidation_5654d05d-82c1-48da-ad8f-161b817f6d41/0.0.45/private/azure-swagger-validation/azureSwaggerValidation/dist/main.js:199603:36)\n' +
    '    at Object.exports.traverseSwaggerAsync (/mnt/vss/_work/_tasks/AzureApiValidation_5654d05d-82c1-48da-ad8f-161b817f6d41/0.0.45/private/azure-swagger-validation/azureSwaggerValidation/dist/main.js:202157:54)\n' +
    '    at async SwaggerExampleValidator.validateOperations (/mnt/vss/_work/_tasks/AzureApiValidation_5654d05d-82c1-48da-ad8f-161b817f6d41/0.0.45/private/azure-swagger-validation/azureSwaggerValidation/dist/main.js:199592:13)\n' +
    '    at async NewModelValidator.validateOperations (/mnt/vss/_work/_tasks/AzureApiValidation_5654d05d-82c1-48da-ad8f-161b817f6d41/0.0.45/private/azure-swagger-validation/azureSwaggerValidation/dist/main.js:200038:9)\n' +
    '    at async /mnt/vss/_work/_tasks/AzureApiValidation_5654d05d-82c1-48da-ad8f-161b817f6d41/0.0.45/private/azure-swagger-validation/azureSwaggerValidation/dist/main.js:205224:13\n' +
    '    at async Object.runScript [as run] (/mnt/vss/_work/_tasks/AzureApiValidation_5654d05d-82c1-48da-ad8f-161b817f6d41/0.0.45/private/azure-swagger-validation/azureSwaggerValidation/dist/main.js:249518:28)\n' +
    '    at async main (/mnt/vss/_work/_tasks/AzureApiValidation_5654d05d-82c1-48da-ad8f-161b817f6d41/0.0.45/private/azure-swagger-validation/azureSwaggerValidation/dist/main.js:249236:9)',
  level: '\x1B[31merror\x1B[39m'
}
```

See https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2004997&view=logs&j=14c5c170-9612-5b44-a650-13d3ca524cf8&t=a1928b1b-77e4-58b6-0247-4cedb38901b4&l=51

**Comment by raych1** [comment]
I should mention that the fix was released in oav but hasn't been released in the swagger PR pipeline yet.

**Comment by raych1** [comment]
@abatishchev, the latest oav version was integrated into swagger PR pipeline.

**Comment by abatishchev** [comment]
I can confirm, it works now. Thanks, Ray!
