### ISSUE TITLE
[LiveValidate RPaaS] Newest image version crashes validation of `networkFunctions` service request

### ISSUE THREAD

**Issue by scbedd** [Azure/oav#993]
image version: `v1.5.0.20230806.1` . reverted back to `1.4.9.20230611.1` to mitigate.

```text
API (response) validation failed for resource 'Microsoft.HybridNetwork/networkFunctions/RunnerCNF' with runtime exception : code 'REQUEST_VALIDATION_ERROR'; message 'An error occurred while validating the live response for operation \"NetworkFunctions_CreateOrUpdate\". The error is:\n TypeError: Cannot read properties of null (reading 'id')\n
    at Object.validate (eval at localCompile (/usr/app/node_modules/ajv/lib/compile/index.js:120:26), <anonymous>:3:1470)\n
    at Object.validate (eval at localCompile (/usr/app/node_modules/ajv/lib/compile/index.js:120:26), <anonymous>:3:2849)\n
    at Object.validate (eval at localCompile (/usr/app/node_modules/ajv/lib/compile/index.js:120:26), <anonymous>:3:1595)\n
    at Object.validate (eval at localCompile (/usr/app/node_modules/ajv/lib/compile/index.js:120:26), <anonymous>:3:770)\n
    at validateSchema (/usr/app/node_modules/oav/dist/lib/swaggerValidator/ajvSchemaValidator.js:91:53)\n
    at exports.validateSwaggerLiveResponse (/usr/app/node_modules/oav/dist/lib/liveValidation/operationValidator.js:86:20)\n
    at LiveValidator.validateLiveResponse (/usr/app/node_modules/oav/dist/lib/liveValidation/liveValidator.js:318:49)\n
    at Validator.validateResponse (/usr/app/dist/src/lib/validator.js:215:49)\n
    at ValidationController.validateResponse (/usr/app/dist/src/controllers/validationController.js:55:28)\n
    at InversifyExpressServer.<anonymous> (/usr/app/node_modules/inversify-express-utils/lib/server.js:202:124)'. Complete validaton result : {\"operationInfo\":{\"operationId\":\"NetworkFunctions_CreateOrUpdate\",\"apiVersion\":\"2021-05-01\"},\"errors\":[],\"runtimeException\":{\"code\":\"REQUEST_VALIDATION_ERROR\",\"message\":\"An error occurred while validating the live response for operation \\\"NetworkFunctions_CreateOrUpdate\\\". The error is:\\n TypeError: Cannot read properties of null (reading 'id')\\n
    at Object.validate (eval at localCompile (/usr/app/node_modules/ajv/lib/compile/index.js:120:26), <anonymous>:3:1470)\\n
    at Object.validate (eval at localCompile (/usr/app/node_modules/ajv/lib/compile/index.js:120:26), <anonymous>:3:2849)\\n
    at Object.validate (eval at localCompile (/usr/app/node_modules/ajv/lib/compile/index.js:120:26), <anonymous>:3:1595)\\n
    at Object.validate (eval at localCompile (/usr/app/node_modules/ajv/lib/compile/index.js:120:26), <anonymous>:3:770)\\n
    at validateSchema (/usr/app/node_modules/oav/dist/lib/swaggerValidator/ajvSchemaValidator.js:91:53)\\n
    at exports.validateSwaggerLiveResponse (/usr/app/node_modules/oav/dist/lib/liveValidation/operationValidator.js:86:20)\\n
    at LiveValidator.validateLiveResponse (/usr/app/node_modules/oav/dist/lib/liveValidation/liveValidator.js:318:49)\\n
    at Validator.validateResponse (/usr/app/dist/src/lib/validator.js:215:49)\\n
    at ValidationController.validateResponse (/usr/app/dist/src/controllers/validationController.js:55:28)\\n
    at InversifyExpressServer.<anonymous> (/usr/app/node_modules/inversify-express-utils/lib/server.js:202:124)\"}}
```

This caused a reversion of production rollout. Need to get payload details from RPaaS folks so that we can repro and issue a fix.

**Comment by scbedd** [comment]
Erroring payload.

```json
{
    "id": "/subscriptions/6c204db9-7efd-4adb-98ac-e982a6e32879/resourceGroups/rgname/providers/Microsoft.HybridNetwork/networkFunctions/nf0001",
    "name": "nf0001",
    "type": "microsoft.hybridnetwork/networkfunctions",
    "location": "eastus2euap",
    "systemData": {
        "createdBy": "alias@microsoft.com",
        "createdByType": "User",
        "createdAt": "2023-08-16T00:47:52.8414851Z",
        "lastModifiedBy": "alias@microsoft.com",
        "lastModifiedByType": "User",
        "lastModifiedAt": "2023-08-16T00:47:52.8414851Z"
    },
    "properties": {
        "provisioningState": "Accepted",
        "device": null,
        "skuName": "cnfsku1",
        "skuType": "EvolvedPacketCore",
        "vendorName": "v1",
        "serviceKey": "6c204db9-7efd-4adb-98ac-e982a6e28084",
        "vendorProvisioningState": "NotProvisioned",
        "managedApplication": null,
        "managedApplicationParameters": {
            "extendedLocation": {
                "Name": "/subscriptions/6c204db9-7efd-4adb-98ac-e982a6e28084/resourceGroups/rgname2/providers/Microsoft.ExtendedLocation/customLocations/localCl011",
                "Type": "CustomLocation"
            },
            "vendorConfigurations": {
                "releaseName": "cnf-runner-test",
                "targetNamespace": "cnf-runner-test",
                "values": "{\"repoBase\":\"xyz.azurecr.io3/\"}"
            },
            "userConfigurations": {}
        },
        "networkFunctionUserConfigurations": null
    }
}
```

**Comment by scbedd** [comment]
[Created branch](https://devdiv.visualstudio.com/DevDiv/_git/openapi-platform?version=GBfeature%2Fsupport-networkfunctions-call)

Debugging through to `oav`.

**Comment by scbedd** [comment]
This is caused by _some_ change in oav. `validate-v2` image versions before `oav` update `3.2.8` are solid. It's after that are the problem. Given that this is strictly a crash in oav, going to xfer this issue there.

**Comment by scbedd** [comment]
#### Version that began blowing up:

**Tag**: `v1.5.0.20230806.1`
**SourceSHA**: `36a3172bd67990016e8cbb8d1aa8fdc8d6abebdf`

#### Version we know also doesn't work:

**Tag**: `v1.4.10.20230709.1`
**SourceSHA**: `6d0dff012e247dcf0120638f2e7a08ba612a4140`

#### Version we went back to:

**Tag**: `1.4.9.20230611.01`
**SourceSHA**: `ac799db47657c337e55db96e37ed09f21b6347c9`

Cherry-pickable SHA including test-case for this situation `be55293f8e9ab4193c54c117edbd9a17336540a9`.

```
docker pull azopenapitest.azurecr.io/internal/openapi/validate-v2:v1.5.0.20230806.1
docker inspect azopenapitest.azurecr.io/internal/openapi/validate-v2:v1.5.0.20230806.1
"Labels": {
    "com.visualstudio.devdiv.image.build.buildnumber": "20230806.1",
    "com.visualstudio.devdiv.image.build.builduri": "vstfs:///Build/Build/8209724",
    "com.visualstudio.devdiv.image.build.definitionname": "openapi-validate-CI",
    "com.visualstudio.devdiv.image.build.repository.name": "openapi-platform",
    "com.visualstudio.devdiv.image.build.repository.uri": "https://devdiv.visualstudio.com/DevDiv/_git/openapi-platform",
    "com.visualstudio.devdiv.image.build.sourcebranchname": "main",
    "com.visualstudio.devdiv.image.build.sourceversion": "36a3172bd67990016e8cbb8d1aa8fdc8d6abebdf",
    "com.visualstudio.devdiv.image.system.teamfoundationcollectionuri": "https://devdiv.visualstudio.com/",
    "com.visualstudio.devdiv.image.system.teamproject": "DevDiv",
    "image.base.ref.name": "mcr.microsoft.com/mirror/docker/library/node:18-alpine"
}

docker pull azopenapitest.azurecr.io/internal/openapi/validate-v2:v1.4.10.20230709.1
docker inspect azopenapitest.azurecr.io/internal/openapi/validate-v2:v1.4.10.20230709.1
"Labels": {
    "com.visualstudio.devdiv.image.build.buildnumber": "20230709.1",
    "com.visualstudio.devdiv.image.build.builduri": "vstfs:///Build/Build/8042993",
    "com.visualstudio.devdiv.image.build.definitionname": "openapi-validate-CI",
    "com.visualstudio.devdiv.image.build.repository.name": "openapi-platform",
    "com.visualstudio.devdiv.image.build.repository.uri": "https://devdiv.visualstudio.com/DevDiv/_git/openapi-platform",
    "com.visualstudio.devdiv.image.build.sourcebranchname": "main",
    "com.visualstudio.devdiv.image.build.sourceversion": "6d0dff012e247dcf0120638f2e7a08ba612a4140",
    "com.visualstudio.devdiv.image.system.teamfoundationcollectionuri": "https://devdiv.visualstudio.com/",
    "com.visualstudio.devdiv.image.system.teamproject": "DevDiv",
    "image.base.ref.name": "mcr.microsoft.com/mirror/docker/library/node:18-alpine"
}

docker pull azopenapi.azurecr.io/internal/openapi/validate-v2:v1.4.9.20230611.1
docker inspect azopenapi.azurecr.io/internal/openapi/validate-v2:v1.4.9.20230611.1
"Labels": {
    "com.visualstudio.devdiv.image.build.buildnumber": "20230611.1",
    "com.visualstudio.devdiv.image.build.builduri": "vstfs:///Build/Build/7901577",
    "com.visualstudio.devdiv.image.build.definitionname": "openapi-validate-CI",
    "com.visualstudio.devdiv.image.build.repository.name": "openapi-platform",
    "com.visualstudio.devdiv.image.build.repository.uri": "https://devdiv.visualstudio.com/DevDiv/_git/openapi-platform",
    "com.visualstudio.devdiv.image.build.sourcebranchname": "main",
    "com.visualstudio.devdiv.image.build.sourceversion": "ac799db47657c337e55db96e37ed09f21b6347c9",
    "com.visualstudio.devdiv.image.system.teamfoundationcollectionuri": "https://devdiv.visualstudio.com/",
    "com.visualstudio.devdiv.image.system.teamproject": "DevDiv",
    "image.base.digest": "sha256:f41850f74ff16a33daff988e2ea06ef8f5daeb6fb84913c7df09552a98caba09",
    "image.base.ref.name": "mcr.microsoft.com/mirror/docker/library/node:18-alpine"
}


```

**Comment by scbedd** [comment]
We are passing `isArmCall: true`...which causes the failure to parse due to the additional ARM validation rules being added on the fly in `ajvSchemaValidator.ts`.

Need to dig into why the additional ARM validation rules are doing this, and possible come up with a different way to implement it.

**Comment by scbedd** [comment]
Will open a new issue to cover the investigation into `isArmCall`.
